### ISSUE TITLE
non-interactive publish capability

### ISSUE THREAD

**Issue by glarivie** [pikapkg/pack#30]
Hi,
I'm looking for a way to publish my package during a CI/CD job but without interact with `publish` command.

Thanks for your help.

**Comment by ryaninvents** [comment]
Hello @hqro ,

Depends on what you want to do. Personally, I've committed to [Semantic Release](https://semantic-release.gitbook.io), so all I need to do to publish is merge to my publish branch -- it determines whether to publish major/minor/patch based on "smart" commit messages.

I think my [`plugin-bundle-zip-node`](https://github.com/ryaninvents/plugin-bundle-zip) project is a good example of using Semantic Release together with Pack. My `.circleci/config.yml` refers to a context called "gh-npm-public"; this populates GitHub and npm API keys. You can just as easily set up two environment variables, `NPM_TOKEN` and `GH_TOKEN`.

Relevant parts of `package.json` that you'll want (careful copying, since you may want to choose different options):
- Dev dependencies:
  - `@pika/pack` and whichever builders you want to use
  - `semantic-release` and all `@semantic-release/*` packages
- `@pika/pack` configuration
- `release`: this specifies Semantic Release config
- `scripts`:
  - `build` to run Pika Pack
  - `semantic-release` to run the release

You can test your setup by running `npx semantic-release --dry-run` in your repo, after you've configured it.

**Comment by glarivie** [comment]
I didn't know *semantic release*, it seems to be really powerful.
But I would have liked to know if it was possible to use the command `pika publish` in a *non-interactive* way ?

This is a copy of my `.circleci/config.yml` and I usually change the version of the package by hand and release it with `yarn publish --non-interactive`

```yaml
steps:
  - checkout
  - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > $HOME/.npmrc # Login to private repo
  - run: yarn install
  - run: yarn build # pika build
  - run: yarn publish --non-interactive
```

**Comment by glarivie** [comment]
This is the final solution for me

```yaml
steps:
  - *attach_workspace
  - run: yarn build # pika build
  - run: apt update -y && apt install -y jq
  - run: |
      cd ./pkg
      VERSION="$(cat package.json | jq -r .version)-$CIRCLE_BUILD_NUM"
      yarn version --new-version $VERSION --no-git-tag-version --no-commit-hooks
      yarn publish --non-interactive --tag latest --access restricted
```
